config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :rated do
    member do
      patch :rate
      patch :cancel_rate
    end
  end

  resources :questions, concerns: [:rated], shallow: true do
    resources :comments, defaults: {commentable: 'questions'}, only: [:create]
    resources :answers, shallow: true do
      resources :comments, defaults: {commentable: 'answers'}, only: [:create]
      patch :set_best
    end
  end

  resources :answers, concerns: [:rated], only: [:rate, :cancel_rate]

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  get '/search' => 'search#search'
  mount ActionCable.server => "/cable"
end

app/models/search.rb
class Search
  SEARCH_OBJECTS = %w(Questions Answers Comments Users)

  def self.search_result(search_string, search_object)
    string_with_escape = ThinkingSphinx::Query.escape(search_string)
    if SEARCH_OBJECTS.include?(search_object)
       search_object.singularize.constantize.search(string_with_escape)
    else
      ThinkingSphinx.search(string_with_escape)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource
  respond_to :html

  def search
    respond_with(@search_results = Search.search_result(params[:search_string], params[:search_object]))
  end
end

app/views/search/_search.html.haml
= form_tag search_path, method: :get, class: 'navbar-form' do
  .form-group
    = text_field_tag :search_string, params[:search_string], required: true, class: "form-control"
    = select_tag :search_object, options_for_select(Search::SEARCH_OBJECTS, params[:search_object]), class: "form-control", prompt: 'Everywhere'
    = submit_tag 'Search', class: "btn btn-default"

app/views/search/search.html.haml
%h3= "#{@search_results.size} objects found:"
-@search_results.each do |result|
  .well= link_to result.class.to_s, result rescue result.to_s