config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :rated do
    member do
      patch :rate
      patch :cancel_rate
    end
  end

  resources :questions, concerns: [:rated], shallow: true do
    resources :comments, defaults: {commentable: 'questions'}, only: [:create]
    resources :answers, shallow: true do
      resources :comments, defaults: {commentable: 'answers'}, only: [:create]
      patch :set_best
    end
  end

  resources :answers, concerns: [:rated], only: [:rate, :cancel_rate]

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  get '/search' => 'search#search'
  mount ActionCable.server => "/cable"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include HasAttachments
  include HasRates
  include HasUser
  include HasComments

  belongs_to :question

  validates :body, presence: true
  validate :best_only_one

  after_commit :notify_subscribers, on: :create

  def set_best
    Answer.transaction do
      Answer.where(question_id: question).where(best: true).update_all(best: false)
      update_attributes(best: true)
    end
  end

  private

  def best_only_one
    if best != best_was && question.answers.where(best: true).exists?
      errors.add(:base, 'Must be the best only one answer')
    end
  end

  def notify_subscribers
    NewAnswerJob.perform_later(self)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Rated
  before_action :authenticate_user!, only: [:new, :create]
  before_action :load_answer, only: [:destroy, :update, :set_best]
  before_action :load_question, only: [:update, :set_best, :create]
  after_action :publish_answer, only: [:create]

  respond_to :js, :json
  authorize_resource
  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def set_best
    authorize! :set_best, @answer
    respond_with(@answer.set_best)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :_destroy])
  end

  def load_answer
    @answer = Answer.find(params[:id] || params[:answer_id])
  end

  def load_question
    @question = params[:question_id] ? Question.find(params[:question_id]) : @answer.question
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("questions/#{@answer.question_id}/answers",
        {
          answer: @answer,
          user_email: @answer.user.email,
          attachments: @answer.attachments
        }
      )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource
  before_action :load_question, except: :show
  def index
    @answers= @question.answers
    respond_with @answers, each_serializer: AnswerShortSerializer
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.create(answer_params.merge(question: @question, user: current_resource_owner))
    respond_with @answer
  end

  private
  def answer_params
    params.require(:answer).permit(:body)
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
.answer{id: "answer-#{answer.id}" }
  .panel.panel-primary
    .panel-heading
      = answer.best ? "Best answer" : "answer"
      = answer.user.email
    .panel-body
      .row
        .col-md-2

          = render 'shared/rate', item: answer

        .col-md-10
          = answer.body.html_safe
          - if can?(:set_best, answer)
            = link_to 'Best answer', answer_set_best_path(question_id: @question, answer_id: answer), class: 'btn btn-primary', remote: true, method: :patch

          - if can?(:destroy, answer)
            = link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' }, remote: true
          - if can?(:update, answer)
            = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }


      - if answer.attachments.length > 0
        %p Attachments:
        %ul
          - answer.attachments.each do |attachment|
            .attachment{id: "attachment-#{attachment.id}"}
              %li= link_to attachment.file.identifier, attachment.file.url
              - if can?(:destroy, attachment)
                .delete_answer_file= link_to 'Delete', attachment, method: :delete, data: { confirm: 'Are you sure?' }, remote: true

      = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"}  do |f|
        .well
          = f.label :body, 'Answer'
          = f.text_area :body, class: "form-control"
          = f.submit 'Update', class: "btn btn-primary"

    .list-comment-answer{id: "list-comment-answer-#{answer.id}" }
      = render 'comments/list', commentable: answer

    - if user_signed_in?
      = form_for [answer, Comment.new], remote: :true, html: { id: "comment-answer-#{answer.id}", class: "comment-answer"} do |f|
        = f.text_area :body, required: true, class: "form-control answer-comment-body"
        = f.submit 'Send comment', class: "btn btn-info"
        = link_to 'Cancel', '', class: 'cancel-answer-comment-link', data: { answer_id: answer.id }

      = link_to 'Add comment', '', class: 'add-answer-comment-link', data: { answer_id: answer.id }, id: "add-answer-comment-link-#{answer.id}"

app/views/answers/_list.html.haml
- @question.answers.order(best: :desc).each_with_index do |answer, index|
  = render 'answers/answer', answer: answer, index: index

app/views/answers/create.js.erb
$('.errors').html('');

<% if @answer.valid? %>
  if ($('#answer-<%= @answer.id %>')[0] === undefined) {
    $('.answers').append("<%= j render @answer, index: @question.answers.count - 1 %>")
  }
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });

<%else%>
  $('.answers').append("<%= j render 'shared/error_message', item: @answer %>");
<%end%>

$('.new-answer-body').val('');

app/views/answers/destroy.js.erb
<% unless @answer.persisted? %>
  $('#answer-<%= @answer.id %>').remove();
<%end%>

app/views/answers/set_best.js.erb
<% if @answer.valid? %>
  $('.answers').html("<%= j render 'answers/list' %>");
    $('.edit-answer-link').click(function(e) {
      e.preventDefault();
      $(this).hide();
      answer_id = $(this).data('answerId');
      $('form#edit-answer-' + answer_id).show();
  });
<%else%>
  $('#answer-<%= @answer.id %>').append("<%= j render 'shared/error_message', item: @answer %>");
<%end%>

app/views/answers/update.js.erb
$('.errors').html('');

<% if @answer.valid? %>
  $('#answer-<%= @answer.id %>').html("<%= j render @answer %>");
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
  $('.add-answer-comment-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    $('.comment-answer').show();
  });
<%else%>
  $('#answer-<%= @answer.id %>').append("<%= j render 'shared/error_message', item: @answer %>");
<%end%>