config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :rated do
    member do
      patch :rate
      patch :cancel_rate
    end
  end

  resources :questions, concerns: [:rated], shallow: true do
    resources :comments, defaults: {commentable: 'questions'}, only: [:create]
    resources :answers, shallow: true do
      resources :comments, defaults: {commentable: 'answers'}, only: [:create]
      patch :set_best
    end
  end

  resources :answers, concerns: [:rated], only: [:rate, :cancel_rate]

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  get '/search' => 'search#search'
  mount ActionCable.server => "/cable"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_subscription, only: [:destroy]
  authorize_resource
  respond_to :js

  def create
    respond_with(@subscription = current_user.subscriptions.create(subscription_params), template: 'subscriptions/action')
  end

  def destroy
    respond_with(@subscription.destroy, template: 'subscriptions/action')
  end

  private
  def subscription_params
    params.require(:subscription).permit(:question_id)
  end

  def load_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_subscription.html.haml
-if can?(:create, Subscription.new) && !question.subscribed_by?(current_user)
  = link_to 'Subscribe', subscriptions_path(subscription: {question_id: question.id}),
  method: :post, remote: true

-subscription = question.find_subscription(current_user)
-if can?(:destroy, subscription) && question.subscribed_by?(current_user)
  = link_to 'Unsubscribe', subscription, method: :delete, remote: true

app/views/subscriptions/action.js.erb
<% if @subscription.errors.present? %>
  <% @subscription.errors.full_messages.each do |message| %>
    $('.errors').html('<%= j message %>')
  <% end %>
<% else %>
    $("#subscription").html('<%= j render 'subscriptions/subscription',question: @subscription.question %>')
<% end %>