config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :rated do
    member do
      patch :rate
      patch :cancel_rate
    end
  end

  resources :questions, concerns: [:rated], shallow: true do
    resources :comments, defaults: {commentable: 'questions'}, only: [:create]
    resources :answers, shallow: true do
      resources :comments, defaults: {commentable: 'answers'}, only: [:create]
      patch :set_best
    end
  end

  resources :answers, concerns: [:rated], only: [:rate, :cancel_rate]

  resources :attachments, only: :destroy

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, shallow: true do
        resources :answers
      end
    end
  end
  resources :subscriptions, only: [:create, :destroy]
  get '/search' => 'search#search'
  mount ActionCable.server => "/cable"
end

app/views/layouts/_header.haml
%nav.navbar.navbar-inverse.navbar-default.navbar-static-top{role: "navigation"}
  .container-fluid
    .navbar-header
      = link_to "Question & Answer", root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav
      - if user_signed_in?
        %li
          = link_to 'All questions', questions_path
        %li
          = link_to 'My questions', questions_path(only_me: true)
    %ul.nav.navbar-nav.navbar-right
      %li
        %li
          = link_to 'New question', new_question_path
      %li
        = render 'search/search'
      - if user_signed_in?
        %p.navbar-text= current_user.email
        %li
          = link_to destroy_user_session_path, method: "delete" do
            %span.glyphicon.glyphicon-log-out
            Log out
      - else
        %li
          = link_to new_registration_path('user') do
            %span.glyphicon.glyphicon-user
            Sign Up
        %li
          = link_to new_user_session_path do
            %span.glyphicon.glyphicon-log-in
            Login

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Qna5
    = csrf_meta_tags
    = Gon::Base.render_data
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/header'
    .container
      = render 'shared/flash'
      = yield